[template]
cargo_generate_version = ">=0.9.0"
description = "A Pico2 project template with Embassy or RP-HAL"

[hooks]
pre = ["cargo-generate/prehook.rhai"]

[placeholders.hal]
type = "string"
prompt = "Which HAL?"
choices = ["rp-hal", "embassy"]
default = "embassy"

[placeholders.defmt]
type = "bool"
prompt = "Enable defmt logging?"
default = true

[placeholders.flashcap]
type = "string"
prompt = "How much flash?"
choices = ["2MB", "4MB"]
default = "4MB"